/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as TabsIndexRouteImport } from './routes/_tabs/index'
import { Route as TabsRepsRouteImport } from './routes/_tabs/reps'
import { Route as TabsLegacyRouteImport } from './routes/_tabs/legacy'
import { Route as TabsImpactsRouteImport } from './routes/_tabs/impacts'
import { Route as TabsFeedSettingsRouteImport } from './routes/_tabs/feed-settings'
import { Route as TabsDiscussRouteImport } from './routes/_tabs/discuss'
import { Route as TabsBillsRouteImport } from './routes/_tabs/bills'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsIndexRoute = TabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TabsRoute,
} as any)
const TabsRepsRoute = TabsRepsRouteImport.update({
  id: '/reps',
  path: '/reps',
  getParentRoute: () => TabsRoute,
} as any)
const TabsLegacyRoute = TabsLegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => TabsRoute,
} as any)
const TabsImpactsRoute = TabsImpactsRouteImport.update({
  id: '/impacts',
  path: '/impacts',
  getParentRoute: () => TabsRoute,
} as any)
const TabsFeedSettingsRoute = TabsFeedSettingsRouteImport.update({
  id: '/feed-settings',
  path: '/feed-settings',
  getParentRoute: () => TabsRoute,
} as any)
const TabsDiscussRoute = TabsDiscussRouteImport.update({
  id: '/discuss',
  path: '/discuss',
  getParentRoute: () => TabsRoute,
} as any)
const TabsBillsRoute = TabsBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => TabsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof TabsIndexRoute
  '/welcome': typeof WelcomeRoute
  '/bills': typeof TabsBillsRoute
  '/discuss': typeof TabsDiscussRoute
  '/feed-settings': typeof TabsFeedSettingsRoute
  '/impacts': typeof TabsImpactsRoute
  '/legacy': typeof TabsLegacyRoute
  '/reps': typeof TabsRepsRoute
}
export interface FileRoutesByTo {
  '/welcome': typeof WelcomeRoute
  '/bills': typeof TabsBillsRoute
  '/discuss': typeof TabsDiscussRoute
  '/feed-settings': typeof TabsFeedSettingsRoute
  '/impacts': typeof TabsImpactsRoute
  '/legacy': typeof TabsLegacyRoute
  '/reps': typeof TabsRepsRoute
  '/': typeof TabsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_tabs': typeof TabsRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/_tabs/bills': typeof TabsBillsRoute
  '/_tabs/discuss': typeof TabsDiscussRoute
  '/_tabs/feed-settings': typeof TabsFeedSettingsRoute
  '/_tabs/impacts': typeof TabsImpactsRoute
  '/_tabs/legacy': typeof TabsLegacyRoute
  '/_tabs/reps': typeof TabsRepsRoute
  '/_tabs/': typeof TabsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/welcome'
    | '/bills'
    | '/discuss'
    | '/feed-settings'
    | '/impacts'
    | '/legacy'
    | '/reps'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/welcome'
    | '/bills'
    | '/discuss'
    | '/feed-settings'
    | '/impacts'
    | '/legacy'
    | '/reps'
    | '/'
  id:
    | '__root__'
    | '/_tabs'
    | '/welcome'
    | '/_tabs/bills'
    | '/_tabs/discuss'
    | '/_tabs/feed-settings'
    | '/_tabs/impacts'
    | '/_tabs/legacy'
    | '/_tabs/reps'
    | '/_tabs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TabsRoute: typeof TabsRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/': {
      id: '/_tabs/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TabsIndexRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/reps': {
      id: '/_tabs/reps'
      path: '/reps'
      fullPath: '/reps'
      preLoaderRoute: typeof TabsRepsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/legacy': {
      id: '/_tabs/legacy'
      path: '/legacy'
      fullPath: '/legacy'
      preLoaderRoute: typeof TabsLegacyRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/impacts': {
      id: '/_tabs/impacts'
      path: '/impacts'
      fullPath: '/impacts'
      preLoaderRoute: typeof TabsImpactsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/feed-settings': {
      id: '/_tabs/feed-settings'
      path: '/feed-settings'
      fullPath: '/feed-settings'
      preLoaderRoute: typeof TabsFeedSettingsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/discuss': {
      id: '/_tabs/discuss'
      path: '/discuss'
      fullPath: '/discuss'
      preLoaderRoute: typeof TabsDiscussRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/bills': {
      id: '/_tabs/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof TabsBillsRouteImport
      parentRoute: typeof TabsRoute
    }
  }
}

interface TabsRouteChildren {
  TabsBillsRoute: typeof TabsBillsRoute
  TabsDiscussRoute: typeof TabsDiscussRoute
  TabsFeedSettingsRoute: typeof TabsFeedSettingsRoute
  TabsImpactsRoute: typeof TabsImpactsRoute
  TabsLegacyRoute: typeof TabsLegacyRoute
  TabsRepsRoute: typeof TabsRepsRoute
  TabsIndexRoute: typeof TabsIndexRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsBillsRoute: TabsBillsRoute,
  TabsDiscussRoute: TabsDiscussRoute,
  TabsFeedSettingsRoute: TabsFeedSettingsRoute,
  TabsImpactsRoute: TabsImpactsRoute,
  TabsLegacyRoute: TabsLegacyRoute,
  TabsRepsRoute: TabsRepsRoute,
  TabsIndexRoute: TabsIndexRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  TabsRoute: TabsRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
